### ISSUE TITLE
Feature request: Put in sidebar

### ISSUE THREAD

**Issue by toddrjen** [jupyterlab-contrib/jupyterlab-variableInspector#137]
Currently the variable inspector is a separate tab.  However, jupyterlab has a right sidebar that seems to be specifically for tools like this.  That would allow it to be easily hidden and shown depending on whether you need it at that particular moment.

**Comment by lckr** [comment]
Hey Todd, that's a great suggestion. Coincidentally, I already have a branch where I try this out. I'll try to finish this up in the next days.
