### ISSUE TITLE
fails to install on jupyterlab 3.0.14 windows 10

### ISSUE THREAD

**Issue by besbesmany** [jupyterlab-contrib/jupyterlab-variableInspector#211]
is there a solution or not yet
`pip install lckr-jupyterlab-variableinspector`

it fails and gives

(base) C:\Users\legion>pip install lckr-jupyterlab-variableinspector
Collecting lckr-jupyterlab-variableinspector
  Using cached lckr_jupyterlab_variableinspector-3.0.9.tar.gz (60 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: jupyterlab==3.*,>=3.0.0rc13 in c:\programdata\anaconda3\lib\site-packages (from lckr-jupyterlab-variableinspector) (3.0.14)
Requirement already satisfied: nbclassic~=0.2 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.2.6)
Requirement already satisfied: ipython in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (7.22.0)
Requirement already satisfied: jupyterlab-server~=2.3 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.4.0)
Requirement already satisfied: jupyter-packaging~=0.7 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.7.12)
Requirement already satisfied: jupyter-core in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (4.7.1)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (20.9)
Requirement already satisfied: jinja2>=2.10 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.11.3)
Requirement already satisfied: jupyter-server~=1.4 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.4.1)
Requirement already satisfied: tornado>=6.1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (6.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.10->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.1.1)
Requirement already satisfied: ipython-genutils in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.2.0)
Requirement already satisfied: pywin32>=1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (227)
Requirement already satisfied: nbconvert in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (6.0.7)
Requirement already satisfied: jupyter-client>=6.1.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (6.1.12)
Requirement already satisfied: nbformat in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (5.1.3)
Requirement already satisfied: terminado>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.9.4)
Requirement already satisfied: Send2Trash in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.5.0)
Requirement already satisfied: pyzmq>=17 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (20.0.0)
Requirement already satisfied: prometheus-client in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.10.1)
Requirement already satisfied: anyio>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.2.0)
Requirement already satisfied: traitlets>=4.2.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (5.0.5)
Requirement already satisfied: idna>=2.8 in c:\programdata\anaconda3\lib\site-packages (from anyio>=2.0.2->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.10)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio>=2.0.2->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-client>=6.1.1->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.8.1)
Requirement already satisfied: jsonschema>=3.0.1 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (3.2.0)
Requirement already satisfied: babel in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.9.0)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.25.1)
Requirement already satisfied: json5 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.9.5)
Requirement already satisfied: six>=1.11.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.15.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (20.3.0)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0.1->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (52.0.0.post20210125)
Requirement already satisfied: notebook<7 in c:\programdata\anaconda3\lib\site-packages (from nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (6.3.0)
Requirement already satisfied: ipykernel in c:\programdata\anaconda3\lib\site-packages (from notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (5.3.4)
Requirement already satisfied: argon2-cffi in c:\programdata\anaconda3\lib\site-packages (from notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (20.1.0)
Requirement already satisfied: pywinpty>=0.5 in c:\programdata\anaconda3\lib\site-packages (from terminado>=0.8.3->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi->notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.14.5)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook<7->nbclassic~=0.2->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.20)
Requirement already satisfied: pytz>=2015.7 in c:\programdata\anaconda3\lib\site-packages (from babel->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2021.1)
Requirement already satisfied: pickleshare in c:\programdata\anaconda3\lib\site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (3.0.17)
Requirement already satisfied: backcall in c:\programdata\anaconda3\lib\site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.2.0)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.17.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.4.4)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (4.4.2)
Requirement already satisfied: pygments in c:\programdata\anaconda3\lib\site-packages (from ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.8.1)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.7.1)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.2.5)
Requirement already satisfied: entrypoints>=0.2.2 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.3)
Requirement already satisfied: testpath in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.4.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.5.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.4.3)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.8.4)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.1.2)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (3.3.0)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.7.1)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.4.2)
Requirement already satisfied: async-generator in c:\programdata\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.10)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->nbconvert->jupyter-server~=1.4->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (0.5.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2.4.7)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->jupyterlab-server~=2.3->jupyterlab==3.*,>=3.0.0rc13->lckr-jupyterlab-variableinspector) (1.26.4)
Building wheels for collected packages: lckr-jupyterlab-variableinspector
  Building wheel for lckr-jupyterlab-variableinspector (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Public\Documents\Wondershare\CreatorTemp\tmp1p_38g5g'
       cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-cv5emq2t\lckr-jupyterlab-variableinspector_6e0070ca9a994d3cbcdf7a2ce48bd07b
  Complete output (59 lines):
  running bdist_wheel
  running jsdeps
  running handle_files
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\lckr_jupyterlab_variableinspector
  copying lckr_jupyterlab_variableinspector\_version.py -> build\lib\lckr_jupyterlab_variableinspector
  copying lckr_jupyterlab_variableinspector\__init__.py -> build\lib\lckr_jupyterlab_variableinspector
  running egg_info
  writing lckr_jupyterlab_variableinspector.egg-info\PKG-INFO
  writing dependency_links to lckr_jupyterlab_variableinspector.egg-info\dependency_links.txt
  writing requirements to lckr_jupyterlab_variableinspector.egg-info\requires.txt
  writing top-level names to lckr_jupyterlab_variableinspector.egg-info\top_level.txt
  adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
  reading manifest file 'lckr_jupyterlab_variableinspector.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'jupyter-config\lckr_jupyterlab_variableinspector.json'
  no previously-included directories found matching '**\node_modules'
  no previously-included directories found matching 'lib'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyo' found anywhere in distribution
  warning: no previously-included files matching '.git' found anywhere in distribution
  warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
  writing manifest file 'lckr_jupyterlab_variableinspector.egg-info\SOURCES.txt'
  creating build\lib\lckr_jupyterlab_variableinspector\labextension
  copying lckr_jupyterlab_variableinspector\labextension\package.json -> build\lib\lckr_jupyterlab_variableinspector\labextension
  creating build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\383.79cef97ee2a6919173a6.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\453.8c3e228b049bcae471dc.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\534.879f22f7b76b38ac76c6.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\remoteEntry.311df298e19cc62c55a3.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\style.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector\labextension
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\package.json -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\383.79cef97ee2a6919173a6.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\453.8c3e228b049bcae471dc.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\534.879f22f7b76b38ac76c6.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\remoteEntry.311df298e19cc62c55a3.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\style.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\_version.py -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector
  copying build\lib\lckr_jupyterlab_variableinspector\__init__.py -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector
  running install_data
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data\share
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data\share\jupyter
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data\share\jupyter\labextensions
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data\share\jupyter\labextensions\@lckr
  error: could not create 'build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data\share\jupyter\labextensions\@lckr': The filename or extension is too long
  ----------------------------------------
  ERROR: Failed building wheel for lckr-jupyterlab-variableinspector
Failed to build lckr-jupyterlab-variableinspector
ERROR: Could not build wheels for lckr-jupyterlab-variableinspector which use PEP 517 and cannot be installed directly

**Comment by GabZech** [comment]
This fixed it for me: https://github.com/lckr/jupyterlab-variableInspector/issues/183#issuecomment-817233376

**Comment by fcollonval** [comment]
Please install the latest python package for this extension. You should not need any build.

> Closing as answered
