### ISSUE TITLE
Request: Support for Jupyter Lab 3.1.x

### ISSUE THREAD

**Issue by bschulth** [jupyterlab-contrib/jupyterlab-variableInspector#223]
Would be great to add support for Jupyter Lab 3.1.x

https://github.com/lckr/jupyterlab-variableInspector/blob/master/package.json#L47-L54

https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-1

Thanks!

**Comment by JeremyMullins** [comment]
Just tried to rebuild after installing Variable Inspector in Jupyter Lab 3.1.7 and it fails. Uninstalling Variable Inspector will allow me to rebuild. Here is the log that is made when running "jupyter lab build" in my Python Command Prompt.

[jupyterlab-debug-c2c1h88h.log](https://github.com/lckr/jupyterlab-variableInspector/files/7100517/jupyterlab-debug-c2c1h88h.log)

**Comment by snovaisg** [comment]
Fails on 3.1.12 as well. Would love to be able to use it on 3.1.*

**Comment by bobcolner** [comment]
support for 3.1+ would be great

**Comment by bschulth** [comment]
I did some digging, and it seems like installing via `pip` works:

```sh
/usr/bin/pip install lckr-jupyterlab-variableinspector
jupyter lab build --log-level=DEBUG
jupyter labextension list
```

But installing via `jupyter labextension install`, fails

```sh
jupyter labextension install --no-build @lckr/jupyterlab_variableinspector
jupyter lab build --log-level=DEBUG
jupyter labextension list
```

**Comment by maegul** [comment]
With `JupyterLab 3.1.12` I can confirm the same as @bschulth ... install with `pip` (prebuilt) appears to do the trick.  

Though, I haven't put much use in to see if there are any bugs.

**Comment by bschulth** [comment]
#### Close the issue?
- Given that it works via `pip`, I am happy to have this ticket closed.

**Comment by maegul** [comment]
The installation instructions remain inaccurate (recommending labextension and/or the extension manager).

If not functioning through these means of installation is an issue (I'm not familiar enough with the jupyter world to be sure of that either way), then I'd say that this is a live issue.

Either way, the README should probably reflect the state of affairs if the issue is to be closed (IMO).

**Comment by wikithink** [comment]
not support the jupyterlab 3.2.4，please get some update， thanks

**Comment by fcollonval** [comment]
Please install the extension via the python package for Jupyterlab 3+.

> Closing as answered
