### ISSUE TITLE
ERROR: Package 'ipython' requires a different Python: 3.6.9 not in '>=3.7'

### ISSUE THREAD

**Issue by idiomer** [jupyterlab-contrib/jupyterlab-variableInspector#225]
When I'm executing `pip install lckr-jupyterlab-variableinspector` command, it happens following ERROR. Should I reinstall ipython? Or other options? Could you give me some suggestions. Thanks

```
  ERROR: Package 'ipython' requires a different Python: 3.6.9 not in '>=3.7'
  WARNING: You are using pip version 20.2.3; however, version 21.2.4 is available.
  You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wr4iuipv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://source.cootekos.com/repository/pypi-us-proxy/simple/ -- 'jupyter_packaging~=0.7.9' 'jupyterlab>=3.0.0rc13,==3.*' 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

Here is my env:

root@872638dd6550:/tf# python -V
Python 3.6.9
root@872638dd6550:/tf# ipython -V
7.16.1
root@872638dd6550:/tf# jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.16.1
ipykernel        : 5.1.1
jupyter client   : 6.1.7
jupyter lab      : 3.0.15
nbconvert        : 6.0.6
ipywidgets       : 7.5.1
nbformat         : 5.1.3
traitlets        : 4.3.3

**Comment by fcollonval** [comment]
Closing as obsolete as the minimal supported python version is now 3.8.
