### ISSUE TITLE
Cannot make a new release

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/jupyterlab-variableInspector#312]
```
Getting GitHub connection for jupyterlab-contrib/jupyterlab-variableInspector
Getting permission level for krassowski
HTTP Error 401: Unauthorized
====Error Body====
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/prep_release.py", line 9, in <module>
    setup(False)
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/actions/common.py", line 19, in setup
    return prepare_environment(fetch_draft_release=fetch_draft_release)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/jupyter-server/jupyter_releaser/v2/jupyter_releaser/util.py", line 618, in prepare_environment
    raise RuntimeError(msg) from None
RuntimeError: Could not get user permission level, assuming user was not admin!
```

This might be an issue with `jupyter_releaser` or with GitHub API. We can try releasing another package to see if this is self-contained or not.

CC @martinRenou

**Comment by martinRenou** [comment]
I can have a look at this, maybe the releaser config is somewhat outdated

**Comment by krassowski** [comment]
I compared it against https://github.com/jupyterlab-contrib/jupyterlab_code_formatter where I did a release 2 weeks ago and did not see anything significant in prep release step.

**Comment by krassowski** [comment]
Also just checked that prep-release works fine on `jupyterlab`: https://github.com/jupyterlab/jupyterlab/actions/runs/10632091294/job/29474317851

**Comment by krassowski** [comment]
Another data point, I cannot make a release in `nbdime`: https://github.com/jupyter/nbdime/actions/runs/10633372227/job/29478289663

**Comment by martinRenou** [comment]
Could it be that the `ADMIN_GITHUB_TOKEN` on jupyterlab-contrib is not valid anymore?

**Comment by krassowski** [comment]
I think this is indeed related to `ADMIN_GITHUB_TOKEN`. JupyterLab uses `GITHUB_TOKEN` with https://github.com/jupyter-server/jupyter_releaser/pull/557
